--- #YAML:1.0
name:               Perlbal
version:            1.80
abstract:           Reverse-proxy load balancer and webserver
author:
    - Brad Fitzpatrick <brad@danga.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    base:              0
    BSD::Resource:     0
    Carp:              0
    constant:          0
    Danga::Socket:     1.44
    Errno:             0
    Exporter:          0
    Fcntl:             0
    fields:            0
    File::Path:        0
    File::Temp:        0
    FindBin:           0
    Getopt::Long:      0
    Hash::Util:        0
    HTTP::Date:        0
    HTTP::Request:     0
    HTTP::Response:    0
    IO::File:          0
    IO::Handle:        0
    IO::Select:        0
    IO::Socket::INET:  0
    lib:               0
    LWP::UserAgent:    0
    Scalar::Util:      0
    Socket:            0
    strict:            0
    Sys::Syscall:      0
    Test::More:        0.94
    Time::HiRes:       0
    vars:              0
    warnings:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
