--- #YAML:1.0
name:               Perlbal
version:            1.75
abstract:           Reverse-proxy load balancer and webserver
author:
    - Brad Fitzpatrick <brad@danga.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    BSD::Resource:   0
    Danga::Socket:   1.44
    File::Find:      0
    HTTP::Date:      0
    HTTP::Response:  0
    Sys::Syscall:    0
    Test::More:      0
    Time::HiRes:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
