--- #YAML:1.0
name:                Perlbal
version:             1.72
abstract:            Reverse-proxy load balancer and webserver
license:             ~
author:              
    - Brad Fitzpatrick <brad@danga.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    BSD::Resource:                 0
    Danga::Socket:                 1.44
    File::Find:                    0
    HTTP::Date:                    0
    HTTP::Response:                0
    Sys::Syscall:                  0
    Test::More:                    0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
